# IMPORT LIBARARIES

In [60]:
import pandas as pd
import numpy as np

# LOAD DATASET

In [61]:
df=pd.read_csv("employee_data.csv")

print(df)

    Employee_ID     Name   Age Department    Salary  Experience        City  \
0           101    Ansim  21.0       Data   25000.0         1.0     Chennai
1           102    Aisha   NaN       data   28000.0         2.0     Chennai
2           103    Rahim  24.0         HR       NaN         3.0     chennai
3           104     Sara  22.0         IT   30000.0         NaN  Coimbatore
4           105    Rahim  24.0         HR   32000.0         3.0     Chennai
5           106    Meena  -5.0         IT   35000.0         4.0  Coimbatore
6           107  Fathima  23.0        NaN   29000.0         2.0     Chennai
7           108    Kavin  25.0       Data  500000.0         5.0     CHENNAI
8           109    Priya  22.0         IT   31000.0         2.0  Coimbatore
9           110     Arun   NaN         it   33000.0         3.0     Chennai
10          111    Divya  26.0       Data   36000.0         6.0     Chennai
11          112     Arun   NaN         it   33000.0         3.0     Chennai

    Joining_Year
0           2024
1           2023
2           2022
3           2024
4           2022
5           2021
6           2023
7           2020
8           2024
9           2023
10          2019
11          2023

# DATA OVERVIEW

In [62]:
# 1. Understand the dataset
df.head()

,Employee_ID,Name,Age,Department,Salary,Experience,City,Joining_Year
0,101,Ansim,21.0,Data,25000.0,1.0,Chennai,2024
1,102,Aisha,NaN,data,28000.0,2.0,Chennai,2023
2,103,Rahim,24.0,HR,NaN,3.0,chennai,2022
3,104,Sara,22.0,IT,30000.0,NaN,Coimbatore,2024
4,105,Rahim,24.0,HR,32000.0,3.0,Chennai,2022

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   12 non-null     int64
 1   Name          12 non-null     str
 2   Age           9 non-null      float64
 3   Department    11 non-null     str
 4   Salary        11 non-null     float64
 5   Experience    11 non-null     float64
 6   City          12 non-null     str
 7   Joining_Year  12 non-null     int64
dtypes: float64(3), int64(2), str(3)
memory usage: 900.0 bytes

In [64]:
#To check no.of rows and columns
df.shape

(12, 8)

In [65]:
df.describe()

       Employee_ID        Age         Salary  Experience  Joining_Year
count    12.000000   9.000000      11.000000   11.000000     12.000000
mean    106.500000  20.222222   73818.181818    3.090909   2022.333333
std       3.605551   9.588767  141383.746012    1.445998      1.614330
min     101.000000  -5.000000   25000.000000    1.000000   2019.000000
25%     103.750000  22.000000   29500.000000    2.000000   2021.750000
50%     106.500000  23.000000   32000.000000    3.000000   2023.000000
75%     109.250000  24.000000   34000.000000    3.500000   2023.250000
max     112.000000  26.000000  500000.000000    6.000000   2024.000000

# CHECKING MISSING VALUES

In [66]:
# Check missing values
df.isnull().sum()

Employee_ID     0
Name            0
Age             3
Department      1
Salary          1
Experience      1
City            0
Joining_Year    0
dtype: int64

### HANDLING MISSING VALUES

In [67]:
#Convert the negative age value into NaN
df.loc[df["Age"] == -5, "Age"] = np.nan
print(df['Age'])

0     21.0
1      NaN
2     24.0
3     22.0
4     24.0
5      NaN
6     23.0
7     25.0
8     22.0
9      NaN
10    26.0
11     NaN
Name: Age, dtype: float64

In [68]:
#Replace the Null value using mean in Age column.
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [69]:
#Replace the Null value using mode in Department column.
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

In [70]:
#Replave the Null value using median in Salary column.
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [71]:
#Replace the Null value using mean in Experience column.
df['Experience'] = df['Experience'].fillna(df['Experience'].mean())

In [72]:
#Check the Null values 
df.isnull().sum()

Employee_ID     0
Name            0
Age             0
Department      0
Salary          0
Experience      0
City            0
Joining_Year    0
dtype: int64

# CHECKING DUPLICATE VALUES

In [73]:
#Checking Duplicates
df.duplicated().sum()

np.int64(0)

### HANDLING DUPLICATE VALUES

In [74]:
df.duplicated(
    subset=["Name", "Age", "Department", "Salary", "Experience", "City", "Joining_Year"]
).sum()

np.int64(1)

In [75]:
print(df[df.duplicated(
    subset=["Name", "Age", "Department", "Salary", "Experience", "City", "Joining_Year"],
    keep=False
)])

    Employee_ID  Name     Age Department   Salary  Experience     City  \
9           110  Arun  23.375         it  33000.0         3.0  Chennai
11          112  Arun  23.375         it  33000.0         3.0  Chennai

    Joining_Year
9           2023
11          2023

In [76]:
df = df.drop_duplicates(
    subset=["Name", "Age", "Department", "Salary",
            "Experience", "City", "Joining_Year"]
)

# CHECKING DATATYPES

In [77]:
#Checking Datatypes
df.dtypes

Employee_ID       int64
Name                str
Age             float64
Department          str
Salary          float64
Experience      float64
City                str
Joining_Year      int64
dtype: object

### HANDLING DATATYPES

In [78]:
#Converting Age column datatype into int.
df["Age"] = df["Age"].astype(int)

In [79]:
#Converting Experience column datatype into int.
df["Experience"] = df["Experience"].astype(int)

In [80]:
#Checking Data types.
df.dtypes

Employee_ID       int64
Name                str
Age               int64
Department          str
Salary          float64
Experience        int64
City                str
Joining_Year      int64
dtype: object

## HANDLING INCONSISTENT DATA

In [81]:
#Handle inconsistent data.
df["City"] = df["City"].str.lower().str.strip()

df['City'] = df['City'].map({
    'chennai' : 'Chennai',
    'coimbatore': 'Coimbatore'
})

In [82]:
df["Department"] = df["Department"].str.lower().str.strip()

df['Department'] = df['Department'].map({
    'data':'Data',
    'hr':'HR',
    'it':'IT'
})

## CHECKING OUTLIERS

In [83]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Salary"] < lower) |
    (df["Salary"] > upper)
]

print(outliers)

   Employee_ID   Name  Age Department    Salary  Experience     City  \
7          108  Kavin   25       Data  500000.0           5  Chennai

   Joining_Year
7          2020

# FINAL CLEANED DATASET

In [84]:
print(df)

    Employee_ID     Name  Age Department    Salary  Experience        City  \
0           101    Ansim   21       Data   25000.0           1     Chennai
1           102    Aisha   23       Data   28000.0           2     Chennai
2           103    Rahim   24         HR   32000.0           3     Chennai
3           104     Sara   22         IT   30000.0           3  Coimbatore
4           105    Rahim   24         HR   32000.0           3     Chennai
5           106    Meena   23         IT   35000.0           4  Coimbatore
6           107  Fathima   23       Data   29000.0           2     Chennai
7           108    Kavin   25       Data  500000.0           5     Chennai
8           109    Priya   22         IT   31000.0           2  Coimbatore
9           110     Arun   23         IT   33000.0           3     Chennai
10          111    Divya   26       Data   36000.0           6     Chennai

    Joining_Year
0           2024
1           2023
2           2022
3           2024
4           2022
5           2021
6           2023
7           2020
8           2024
9           2023
10          2019